spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/serverDB
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: og.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true